### PR TITLE
Switch from colorize to colored2 gem for compatibility with other gems

### PR DESCRIPTION
**Pull request by bpollman**
I've had trouble using xcprofiler with other gems in the past as everything else in the fastlane/danger universe seems to use `colored` and `colored2`

xcprofiles use of colorize is quite minimal and its an easy change.

### CODE REVIEW

**Comment by bpollman** [comment]
Hi @giginet, what do you think of this change?

**Review by giginet — APPROVED** [review]

**Comment by giginet** [comment]
@bpollman Great work ✨ 
 Thanks

**Comment by giginet** [comment]
I just released version 0.6.3. Thanks!

**Comment by bpollman** [comment]
@giginet Awesome!

**Pull request merged**
